"url": "https://api.github.com/repos/Mariatta/check_python_cla/issues/27",
      "repository_url": "https://api.github.com/repos/Mariatta/check_python_cla",
      "labels_url": "https://api.github.com/repos/Mariatta/check_python_cla/issues/27/labels{/name}",
      "comments_url": "https://api.github.com/repos/Mariatta/check_python_cla/issues/27/comments",
      "events_url": "https://api.github.com/repos/Mariatta/check_python_cla/issues/27/events",
      "html_url": "https://github.com/Mariatta/check_python_cla/pull/27",
      "id": 379576045,
      "node_id": "MDExOlB1bGxSZXF1ZXN0MjI5OTg2NjQy",
      "number": 27,
      "title": "Update pytest to 3.10.1",
      "user": {
        "login": "pyup-bot",
        "id": 16239342,
        "node_id": "MDQ6VXNlcjE2MjM5MzQy",
        "avatar_url": "https://avatars0.githubusercontent.com/u/16239342?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pyup-bot",
        "html_url": "https://github.com/pyup-bot",
        "followers_url": "https://api.github.com/users/pyup-bot/followers",
        "following_url": "https://api.github.com/users/pyup-bot/following{/other_user}",
        "gists_url": "https://api.github.com/users/pyup-bot/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pyup-bot/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pyup-bot/subscriptions",
        "organizations_url": "https://api.github.com/users/pyup-bot/orgs",
        "repos_url": "https://api.github.com/users/pyup-bot/repos",
        "events_url": "https://api.github.com/users/pyup-bot/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pyup-bot/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [

      ],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2018-11-11T23:28:39Z",
      "updated_at": "2018-11-12T00:14:13Z",
      "closed_at": "2018-11-12T00:14:11Z",
      "author_association": "COLLABORATOR",
      "pull_request": {
        "url": "https://api.github.com/repos/Mariatta/check_python_cla/pulls/27",
        "html_url": "https://github.com/Mariatta/check_python_cla/pull/27",
        "diff_url": "https://github.com/Mariatta/check_python_cla/pull/27.diff",
        "patch_url": "https://github.com/Mariatta/check_python_cla/pull/27.patch"
      },
      "body": "\nThis PR updates [pytest](https://pypi.org/project/pytest) from **3.7.4** to **3.10.1**.\n\n\n\n<details>\n  <summary>Changelog</summary>\n  \n  \n   ### 3.10.1\n   ```\n   ==========================\n\nBug Fixes\n---------\n\n- `4287 &lt;https://github.com/pytest-dev/pytest/issues/4287&gt;`_: Fix nested usage of debugging plugin (pdb), e.g. with pytester&#39;s ``testdir.runpytest``.\n\n\n- `4304 &lt;https://github.com/pytest-dev/pytest/issues/4304&gt;`_: Block the ``stepwise`` plugin if ``cacheprovider`` is also blocked, as one depends on the other.\n\n\n- `4306 &lt;https://github.com/pytest-dev/pytest/issues/4306&gt;`_: Parse ``minversion`` as an actual version and not as dot-separated strings.\n\n\n- `4310 &lt;https://github.com/pytest-dev/pytest/issues/4310&gt;`_: Fix duplicate collection due to multiple args matching the same packages.\n\n\n- `4321 &lt;https://github.com/pytest-dev/pytest/issues/4321&gt;`_: Fix ``item.nodeid`` with resolved symlinks.\n\n\n- `4325 &lt;https://github.com/pytest-dev/pytest/issues/4325&gt;`_: Fix collection of direct symlinked files, where the target does not match ``python_files``.\n\n\n- `4329 &lt;https://github.com/pytest-dev/pytest/issues/4329&gt;`_: Fix TypeError in report_collect with _collect_report_last_write.\n\n\n\nTrivial/Internal Changes\n------------------------\n\n- `4305 &lt;https://github.com/pytest-dev/pytest/issues/4305&gt;`_: Replace byte/unicode helpers in test_capture with python level syntax.\n   ```\n   \n  \n  \n   ### 3.10.0\n   ```\n   ==========================\n\nFeatures\n--------\n\n- `2619 &lt;https://github.com/pytest-dev/pytest/issues/2619&gt;`_: Resume capturing output after ``continue`` with ``__import__(&quot;pdb&quot;).set_trace()``.\n\n  This also adds a new ``pytest_leave_pdb`` hook, and passes in ``pdb`` to the\n  existing ``pytest_enter_pdb`` hook.\n\n\n- `4147 &lt;https://github.com/pytest-dev/pytest/issues/4147&gt;`_: Add ``--sw``, ``--stepwise`` as an alternative to ``--lf -x`` for stopping at the first failure, but starting the next test invocation from that test.  See `the documentation &lt;https://docs.pytest.org/en/latest/cache.htmlstepwise&gt;`__ for more info.\n\n\n- `4188 &lt;https://github.com/pytest-dev/pytest/issues/4188&gt;`_: Make ``--color`` emit colorful dots when not running in verbose mode. Earlier, it would only colorize the test-by-test output if ``--verbose`` was also passed.\n\n\n- `4225 &lt;https://github.com/pytest-dev/pytest/issues/4225&gt;`_: Improve performance with collection reporting in non-quiet mode with terminals.\n\n  The &quot;collecting â€¦&quot; message is only printed/updated every 0.5s.\n\n\n\nBug Fixes\n---------\n\n- `2701 &lt;https://github.com/pytest-dev/pytest/issues/2701&gt;`_: Fix false ``RemovedInPytest4Warning: usage of Session... is deprecated, please use pytest`` warnings.\n\n\n- `4046 &lt;https://github.com/pytest-dev/pytest/issues/4046&gt;`_: Fix problems with running tests in package ``__init__.py`` files.\n\n\n- `4260 &lt;https://github.com/pytest-dev/pytest/issues/4260&gt;`_: Swallow warnings during anonymous compilation of source.\n\n\n- `4262 &lt;https://github.com/pytest-dev/pytest/issues/4262&gt;`_: Fix access denied error when deleting stale directories created by ``tmpdir`` / ``tmp_path``.\n\n\n- `611 &lt;https://github.com/pytest-dev/pytest/issues/611&gt;`_: Naming a fixture ``request`` will now raise a warning: the ``request`` fixture is internal and\n  should not be overwritten as it will lead to internal errors.\n\n- `4266 &lt;https://github.com/pytest-dev/pytest/issues/4266&gt;`_: Handle (ignore) exceptions raised during collection, e.g. with Django&#39;s LazySettings proxy class.\n\n\n\nImproved Documentation\n----------------------\n\n- `4255 &lt;https://github.com/pytest-dev/pytest/issues/4255&gt;`_: Added missing documentation about the fact that module names passed to filter warnings are not regex-escaped.\n\n\n\nTrivial/Internal Changes\n------------------------\n\n- `4272 &lt;https://github.com/pytest-dev/pytest/issues/4272&gt;`_: Display cachedir also in non-verbose mode if non-default.\n\n\n- `4277 &lt;https://github.com/pytest-dev/pytest/issues/4277&gt;`_: pdb: improve message about output capturing with ``set_trace``.\n\n  Do not display &quot;IO-capturing turned off/on&quot; when ``-s`` is used to avoid\n  confusion.\n\n\n- `4279 &lt;https://github.com/pytest-dev/pytest/issues/4279&gt;`_: Improve message and stack level of warnings issued by ``monkeypatch.setenv`` when the value of the environment variable is not a ``str``.\n   ```\n   \n  \n  \n   ### 3.9.3\n   ```\n   =========================\n\nBug Fixes\n---------\n\n- `4174 &lt;https://github.com/pytest-dev/pytest/issues/4174&gt;`_: Fix &quot;ValueError: Plugin already registered&quot; with conftest plugins via symlink.\n\n\n- `4181 &lt;https://github.com/pytest-dev/pytest/issues/4181&gt;`_: Handle race condition between creation and deletion of temporary folders.\n\n\n- `4221 &lt;https://github.com/pytest-dev/pytest/issues/4221&gt;`_: Fix bug where the warning summary at the end of the test session was not showing the test where the warning was originated.\n\n\n- `4243 &lt;https://github.com/pytest-dev/pytest/issues/4243&gt;`_: Fix regression when ``stacklevel`` for warnings was passed as positional argument on python2.\n\n\n\nImproved Documentation\n----------------------\n\n- `3851 &lt;https://github.com/pytest-dev/pytest/issues/3851&gt;`_: Add reference to ``empty_parameter_set_mark`` ini option in documentation of ``pytest.mark.parametrize``\n\n\n\nTrivial/Internal Changes\n------------------------\n\n- `4028 &lt;https://github.com/pytest-dev/pytest/issues/4028&gt;`_: Revert patching of ``sys.breakpointhook`` since it appears to do nothing.\n\n\n- `4233 &lt;https://github.com/pytest-dev/pytest/issues/4233&gt;`_: Apply an import sorter (``reorder-python-imports``) to the codebase.\n\n\n- `4248 &lt;https://github.com/pytest-dev/pytest/issues/4248&gt;`_: Remove use of unnecessary compat shim, six.binary_type\n   ```\n   \n  \n  \n   ### 3.9.2\n   ```\n   =========================\n\nBug Fixes\n---------\n\n- `2909 &lt;https://github.com/pytest-dev/pytest/issues/2909&gt;`_: Improve error message when a recursive dependency between fixtures is detected.\n\n\n- `3340 &lt;https://github.com/pytest-dev/pytest/issues/3340&gt;`_: Fix logging messages not shown in hooks ``pytest_sessionstart()`` and ``pytest_sessionfinish()``.\n\n\n- `3533 &lt;https://github.com/pytest-dev/pytest/issues/3533&gt;`_: Fix unescaped XML raw objects in JUnit report for skipped tests\n\n\n- `3691 &lt;https://github.com/pytest-dev/pytest/issues/3691&gt;`_: Python 2: safely format warning message about passing unicode strings to ``warnings.warn``, which may cause\n  surprising ``MemoryError`` exception when monkey patching ``warnings.warn`` itself.\n\n\n- `4026 &lt;https://github.com/pytest-dev/pytest/issues/4026&gt;`_: Improve error message when it is not possible to determine a function&#39;s signature.\n\n\n- `4177 &lt;https://github.com/pytest-dev/pytest/issues/4177&gt;`_: Pin ``setuptools&gt;=40.0`` to support ``py_modules`` in ``setup.cfg``\n\n\n- `4179 &lt;https://github.com/pytest-dev/pytest/issues/4179&gt;`_: Restore the tmpdir behaviour of symlinking the current test run.\n\n\n- `4192 &lt;https://github.com/pytest-dev/pytest/issues/4192&gt;`_: Fix filename reported by ``warnings.warn`` when using ``recwarn`` under python2.\n   ```\n   \n  \n  \n   ### 3.9.1\n   ```\n   =========================\n\nFeatures\n--------\n\n- `4159 &lt;https://github.com/pytest-dev/pytest/issues/4159&gt;`_: For test-suites containing test classes, the information about the subclassed\n  module is now output only if a higher verbosity level is specified (at least\n  &quot;-vv&quot;).\n   ```\n   \n  \n  \n   ### 3.9.0\n   ```\n   =========================================================================\n\nDeprecations\n------------\n\n- `3616 &lt;https://github.com/pytest-dev/pytest/issues/3616&gt;`_: The following accesses have been documented as deprecated for years, but are now actually emitting deprecation warnings.\n\n  * Access of ``Module``, ``Function``, ``Class``, ``Instance``, ``File`` and ``Item`` through ``Node`` instances. Now\n    users will this warning::\n\n          usage of Function.Module is deprecated, please use pytest.Module instead\n\n    Users should just ``import pytest`` and access those objects using the ``pytest`` module.\n\n  * ``request.cached_setup``, this was the precursor of the setup/teardown mechanism available to fixtures. You can\n    consult `funcarg comparison section in the docs &lt;https://docs.pytest.org/en/latest/funcarg_compare.html&gt;`_.\n\n  * Using objects named ``&quot;Class&quot;`` as a way to customize the type of nodes that are collected in ``Collector``\n    subclasses has been deprecated. Users instead should use ``pytest_collect_make_item`` to customize node types during\n    collection.\n\n    This issue should affect only advanced plugins who create new collection types, so if you see this warning\n    message please contact the authors so they can change the code.\n\n  * The warning that produces the message below has changed to ``RemovedInPytest4Warning``::\n\n          getfuncargvalue is deprecated, use getfixturevalue\n\n\n- `3988 &lt;https://github.com/pytest-dev/pytest/issues/3988&gt;`_: Add a Deprecation warning for pytest.ensuretemp as it was deprecated since a while.\n\n\n\nFeatures\n--------\n\n- `2293 &lt;https://github.com/pytest-dev/pytest/issues/2293&gt;`_: Improve usage errors messages by hiding internal details which can be distracting and noisy.\n\n  This has the side effect that some error conditions that previously raised generic errors (such as\n  ``ValueError`` for unregistered marks) are now raising ``Failed`` exceptions.\n\n\n- `3332 &lt;https://github.com/pytest-dev/pytest/issues/3332&gt;`_: Improve the error displayed when a ``conftest.py`` file could not be imported.\n\n  In order to implement this, a new ``chain`` parameter was added to ``ExceptionInfo.getrepr``\n  to show or hide chained tracebacks in Python 3 (defaults to ``True``).\n\n\n- `3849 &lt;https://github.com/pytest-dev/pytest/issues/3849&gt;`_: Add ``empty_parameter_set_mark=fail_at_collect`` ini option for raising an exception when parametrize collects an empty set.\n\n\n- `3964 &lt;https://github.com/pytest-dev/pytest/issues/3964&gt;`_: Log messages generated in the collection phase are shown when\n  live-logging is enabled and/or when they are logged to a file.\n\n\n- `3985 &lt;https://github.com/pytest-dev/pytest/issues/3985&gt;`_: Introduce ``tmp_path`` as a fixture providing a Path object.\n\n\n- `4013 &lt;https://github.com/pytest-dev/pytest/issues/4013&gt;`_: Deprecation warnings are now shown even if you customize the warnings filters yourself. In the previous version\n  any customization would override pytest&#39;s filters and deprecation warnings would fall back to being hidden by default.\n\n\n- `4073 &lt;https://github.com/pytest-dev/pytest/issues/4073&gt;`_: Allow specification of timeout for ``Testdir.runpytest_subprocess()`` and ``Testdir.run()``.\n\n\n- `4098 &lt;https://github.com/pytest-dev/pytest/issues/4098&gt;`_: Add returncode argument to pytest.exit() to exit pytest with a specific return code.\n\n\n- `4102 &lt;https://github.com/pytest-dev/pytest/issues/4102&gt;`_: Reimplement ``pytest.deprecated_call`` using ``pytest.warns`` so it supports the ``match=&#39;...&#39;`` keyword argument.\n\n  This has the side effect that ``pytest.deprecated_call`` now raises ``pytest.fail.Exception`` instead\n  of ``AssertionError``.\n\n\n- `4149 &lt;https://github.com/pytest-dev/pytest/issues/4149&gt;`_: Require setuptools&gt;=30.3 and move most of the metadata to ``setup.cfg``.\n\n\n\nBug Fixes\n---------\n\n- `2535 &lt;https://github.com/pytest-dev/pytest/issues/2535&gt;`_: Improve error message when test functions of ``unittest.TestCase`` subclasses use a parametrized fixture.\n\n\n- `3057 &lt;https://github.com/pytest-dev/pytest/issues/3057&gt;`_: ``request.fixturenames`` now correctly returns the name of fixtures created by ``request.getfixturevalue()``.\n\n\n- `3946 &lt;https://github.com/pytest-dev/pytest/issues/3946&gt;`_: Warning filters passed as command line options using ``-W`` now take precedence over filters defined in ``ini``\n  configuration files.\n\n\n- `4066 &lt;https://github.com/pytest-dev/pytest/issues/4066&gt;`_: Fix source reindenting by using ``textwrap.dedent`` directly.\n\n\n- `4102 &lt;https://github.com/pytest-dev/pytest/issues/4102&gt;`_: ``pytest.warn`` will capture previously-warned warnings in Python 2. Previously they were never raised.\n\n\n- `4108 &lt;https://github.com/pytest-dev/pytest/issues/4108&gt;`_: Resolve symbolic links for args.\n\n  This fixes running ``pytest tests/test_foo.py::test_bar``, where ``tests``\n  is a symlink to ``project/app/tests``:\n  previously ``project/app/conftest.py`` would be ignored for fixtures then.\n\n\n- `4132 &lt;https://github.com/pytest-dev/pytest/issues/4132&gt;`_: Fix duplicate printing of internal errors when using ``--pdb``.\n\n\n- `4135 &lt;https://github.com/pytest-dev/pytest/issues/4135&gt;`_: pathlib based tmpdir cleanup now correctly handles symlinks in the folder.\n\n\n- `4152 &lt;https://github.com/pytest-dev/pytest/issues/4152&gt;`_: Display the filename when encountering ``SyntaxWarning``.\n\n\n\nImproved Documentation\n----------------------\n\n- `3713 &lt;https://github.com/pytest-dev/pytest/issues/3713&gt;`_: Update usefixtures documentation to clarify that it can&#39;t be used with fixture functions.\n\n\n- `4058 &lt;https://github.com/pytest-dev/pytest/issues/4058&gt;`_: Update fixture documentation to specify that a fixture can be invoked twice in the scope it&#39;s defined for.\n\n\n- `4064 &lt;https://github.com/pytest-dev/pytest/issues/4064&gt;`_: According to unittest.rst, setUpModule and tearDownModule were not implemented, but it turns out they are. So updated the documentation for unittest.\n\n\n- `4151 &lt;https://github.com/pytest-dev/pytest/issues/4151&gt;`_: Add tempir testing example to CONTRIBUTING.rst guide\n\n\n\nTrivial/Internal Changes\n------------------------\n\n- `2293 &lt;https://github.com/pytest-dev/pytest/issues/2293&gt;`_: The internal ``MarkerError`` exception has been removed.\n\n\n- `3988 &lt;https://github.com/pytest-dev/pytest/issues/3988&gt;`_: Port the implementation of tmpdir to pathlib.\n\n\n- `4063 &lt;https://github.com/pytest-dev/pytest/issues/4063&gt;`_: Exclude 0.00 second entries from ``--duration`` output unless ``-vv`` is passed on the command-line.\n\n\n- `4093 &lt;https://github.com/pytest-dev/pytest/issues/4093&gt;`_: Fixed formatting of string literals in internal tests.\n   ```\n   \n  \n  \n   ### 3.8.2\n   ```\n   =========================\n\nDeprecations and Removals\n-------------------------\n\n- `4036 &lt;https://github.com/pytest-dev/pytest/issues/4036&gt;`_: The ``item`` parameter of ``pytest_warning_captured`` hook is now documented as deprecated. We realized only after\n  the ``3.8`` release that this parameter is incompatible with ``pytest-xdist``.\n\n  Our policy is to not deprecate features during bugfix releases, but in this case we believe it makes sense as we are\n  only documenting it as deprecated, without issuing warnings which might potentially break test suites. This will get\n  the word out that hook implementers should not use this parameter at all.\n\n  In a future release ``item`` will always be ``None`` and will emit a proper warning when a hook implementation\n  makes use of it.\n\n\n\nBug Fixes\n---------\n\n- `3539 &lt;https://github.com/pytest-dev/pytest/issues/3539&gt;`_: Fix reload on assertion rewritten modules.\n\n\n- `4034 &lt;https://github.com/pytest-dev/pytest/issues/4034&gt;`_: The ``.user_properties`` attribute of ``TestReport`` objects is a list\n  of (name, value) tuples, but could sometimes be instantiated as a tuple\n  of tuples.  It is now always a list.\n\n\n- `4039 &lt;https://github.com/pytest-dev/pytest/issues/4039&gt;`_: No longer issue warnings about using ``pytest_plugins`` in non-top-level directories when using ``--pyargs``: the\n  current ``--pyargs`` mechanism is not reliable and might give false negatives.\n\n\n- `4040 &lt;https://github.com/pytest-dev/pytest/issues/4040&gt;`_: Exclude empty reports for passed tests when ``-rP`` option is used.\n\n\n- `4051 &lt;https://github.com/pytest-dev/pytest/issues/4051&gt;`_: Improve error message when an invalid Python expression is passed to the ``-m`` option.\n\n\n- `4056 &lt;https://github.com/pytest-dev/pytest/issues/4056&gt;`_: ``MonkeyPatch.setenv`` and ``MonkeyPatch.delenv`` issue a warning if the environment variable name is not ``str`` on Python 2.\n\n  In Python 2, adding ``unicode`` keys to ``os.environ`` causes problems with ``subprocess`` (and possible other modules),\n  making this a subtle bug specially susceptible when used with ``from __future__ import unicode_literals``.\n\n\n\nImproved Documentation\n----------------------\n\n- `3928 &lt;https://github.com/pytest-dev/pytest/issues/3928&gt;`_: Add possible values for fixture scope to docs.\n   ```\n   \n  \n  \n   ### 3.8.1\n   ```\n   =========================\n\nBug Fixes\n---------\n\n- `3286 &lt;https://github.com/pytest-dev/pytest/issues/3286&gt;`_: ``.pytest_cache`` directory is now automatically ignored by Git. Users who would like to contribute a solution for other SCMs please consult/comment on this issue.\n\n\n- `3749 &lt;https://github.com/pytest-dev/pytest/issues/3749&gt;`_: Fix the following error during collection of tests inside packages::\n\n      TypeError: object of type &#39;Package&#39; has no len()\n\n\n- `3941 &lt;https://github.com/pytest-dev/pytest/issues/3941&gt;`_: Fix bug where indirect parametrization would consider the scope of all fixtures used by the test function to determine the parametrization scope, and not only the scope of the fixtures being parametrized.\n\n\n- `3973 &lt;https://github.com/pytest-dev/pytest/issues/3973&gt;`_: Fix crash of the assertion rewriter if a test changed the current working directory without restoring it afterwards.\n\n\n- `3998 &lt;https://github.com/pytest-dev/pytest/issues/3998&gt;`_: Fix issue that prevented some caplog properties (for example ``record_tuples``) from being available when entering the debugger with ``--pdb``.\n\n\n- `3999 &lt;https://github.com/pytest-dev/pytest/issues/3999&gt;`_: Fix ``UnicodeDecodeError`` in python2.x when a class returns a non-ascii binary ``__repr__`` in an assertion which also contains non-ascii text.\n\n\n\nImproved Documentation\n----------------------\n\n- `3996 &lt;https://github.com/pytest-dev/pytest/issues/3996&gt;`_: New `Deprecations and Removals &lt;https://docs.pytest.org/en/latest/deprecations.html&gt;`_ page shows all currently\n  deprecated features, the rationale to do so, and alternatives to update your code. It also list features removed\n  from pytest in past major releases to help those with ancient pytest versions to upgrade.\n\n\n\nTrivial/Internal Changes\n------------------------\n\n- `3955 &lt;https://github.com/pytest-dev/pytest/issues/3955&gt;`_: Improve pre-commit detection for changelog filenames\n\n\n- `3975 &lt;https://github.com/pytest-dev/pytest/issues/3975&gt;`_: Remove legacy code around im_func as that was python2 only\n   ```\n   \n  \n  \n   ### 3.8.0\n   ```\n   =========================\n\nDeprecations and Removals\n-------------------------\n\n- `2452 &lt;https://github.com/pytest-dev/pytest/issues/2452&gt;`_: ``Config.warn`` and ``Node.warn`` have been\n  deprecated, see `&lt;https://docs.pytest.org/en/latest/deprecations.htmlconfig-warn-and-node-warn&gt;`_ for rationale and\n  examples.\n\n- `3936 &lt;https://github.com/pytest-dev/pytest/issues/3936&gt;`_: ``pytest.mark.filterwarnings`` second parameter is no longer regex-escaped,\n  making it possible to actually use regular expressions to check the warning message.\n\n  **Note**: regex-escaping the match string was an implementation oversight that might break test suites which depend\n  on the old behavior.\n\n\n\nFeatures\n--------\n\n- `2452 &lt;https://github.com/pytest-dev/pytest/issues/2452&gt;`_: Internal pytest warnings are now issued using the standard ``warnings`` module, making it possible to use\n  the standard warnings filters to manage those warnings. This introduces ``PytestWarning``,\n  ``PytestDeprecationWarning`` and ``RemovedInPytest4Warning`` warning types as part of the public API.\n\n  Consult `the documentation &lt;https://docs.pytest.org/en/latest/warnings.htmlinternal-pytest-warnings&gt;`__ for more info.\n\n\n- `2908 &lt;https://github.com/pytest-dev/pytest/issues/2908&gt;`_: ``DeprecationWarning`` and ``PendingDeprecationWarning`` are now shown by default if no other warning filter is\n  configured. This makes pytest more compliant with\n  `PEP-0506 &lt;https://www.python.org/dev/peps/pep-0565/recommended-filter-settings-for-test-runners&gt;`_. See\n  `the docs &lt;https://docs.pytest.org/en/latest/warnings.htmldeprecationwarning-and-pendingdeprecationwarning&gt;`_ for\n  more info.\n\n\n- `3251 &lt;https://github.com/pytest-dev/pytest/issues/3251&gt;`_: Warnings are now captured and displayed during test collection.\n\n\n- `3784 &lt;https://github.com/pytest-dev/pytest/issues/3784&gt;`_: ``PYTEST_DISABLE_PLUGIN_AUTOLOAD`` environment variable disables plugin auto-loading when set.\n\n\n- `3829 &lt;https://github.com/pytest-dev/pytest/issues/3829&gt;`_: Added the ``count`` option to ``console_output_style`` to enable displaying the progress as a count instead of a percentage.\n\n\n- `3837 &lt;https://github.com/pytest-dev/pytest/issues/3837&gt;`_: Added support for &#39;xfailed&#39; and &#39;xpassed&#39; outcomes to the ``pytester.RunResult.assert_outcomes`` signature.\n\n\n\nBug Fixes\n---------\n\n- `3911 &lt;https://github.com/pytest-dev/pytest/issues/3911&gt;`_: Terminal writer now takes into account unicode character width when writing out progress.\n\n\n- `3913 &lt;https://github.com/pytest-dev/pytest/issues/3913&gt;`_: Pytest now returns with correct exit code (EXIT_USAGEERROR, 4) when called with unknown arguments.\n\n\n- `3918 &lt;https://github.com/pytest-dev/pytest/issues/3918&gt;`_: Improve performance of assertion rewriting.\n\n\n\nImproved Documentation\n----------------------\n\n- `3566 &lt;https://github.com/pytest-dev/pytest/issues/3566&gt;`_: Added a blurb in usage.rst for the usage of -r flag which is used to show an extra test summary info.\n\n\n- `3907 &lt;https://github.com/pytest-dev/pytest/issues/3907&gt;`_: Corrected type of the exceptions collection passed to ``xfail``: ``raises`` argument accepts a ``tuple`` instead of ``list``.\n\n\n\nTrivial/Internal Changes\n------------------------\n\n- `3853 &lt;https://github.com/pytest-dev/pytest/issues/3853&gt;`_: Removed ``&quot;run all (no recorded failures)&quot;`` message printed with ``--failed-first`` and ``--last-failed`` when there are no failed tests.\n   ```\n   \n  \n</details>\n\n\n \n\n<details>\n  <summary>Links</summary>\n  \n  - PyPI: https://pypi.org/project/pytest\n  - Changelog: https://pyup.io/changelogs/pytest/\n  - Homepage: https://docs.pytest.org/en/latest/\n</details>\n\n",
      "score": 1.0
    }
  ]
}